"""added more rows for table leave_balances

Revision ID: 4cfd1c53186b
Revises: b178a8aa2146
Create Date: 2025-10-13 00:07:40.581363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfd1c53186b'
down_revision: Union[str, Sequence[str], None] = 'b178a8aa2146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balances', sa.Column('used_days', sa.Numeric(precision=7, scale=2), nullable=False))
    op.add_column('leave_balances', sa.Column('weekly_hours', sa.Float(), nullable=False))
    op.add_column('leave_balances', sa.Column('monthly_hours', sa.Float(), nullable=False))
    op.add_column('leave_balances', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.drop_index('uq_leave_user__year', table_name='leave_balances')
    op.create_index('uq_leave_user_year_type', 'leave_balances', ['user_id', 'leave_type', 'year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_leave_user_year_type', table_name='leave_balances')
    op.create_index('uq_leave_user__year', 'leave_balances', ['user_id', 'leave_type', 'year'], unique=True)
    op.drop_column('leave_balances', 'last_updated')
    op.drop_column('leave_balances', 'monthly_hours')
    op.drop_column('leave_balances', 'weekly_hours')
    op.drop_column('leave_balances', 'used_days')
    # ### end Alembic commands ###
