"""add total_days column

Revision ID: aec23bd66378
Revises: 4cfd1c53186b
Create Date: 2025-10-15 10:28:32.723222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec23bd66378'
down_revision: Union[str, Sequence[str], None] = '4cfd1c53186b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_balances', sa.Column('total_days', sa.Numeric(precision=7, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_balances', 'total_days')
    # ### end Alembic commands ###
